openapi: 3.0.1
info:
  description: API of the Flakkee Verhuizers application
  title: Flakkee Verhuizers
  version: "1.0"
servers:
  - description: default localhost-8080
    url: http://localhost:8080/
tags:
  - description: Flakkee Verhuizers controller
    name: Flakkee Verhuizers
paths:
  /address-types:
    get:
      operationId: findAllAddressTypes
      parameters:
        - in: query
          name: sort
          required: false
          schema:
            type: string
        - in: query
          name: order
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AddressTypesResponse'
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /house-types:
    get:
      operationId: findAllHouseTypes
      parameters:
        - in: query
          name: sort
          required: false
          schema:
            type: string
        - in: query
          name: order
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HouseTypesResponse'
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /import/inventory-data:
    post:
      operationId: uploadCategoryCSV
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        "200":
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /import/spaces:
    post:
      operationId: uploadSpacesCSV
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        "200":
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /item-categories:
    get:
      operationId: findAllCategories
      parameters:
        - in: query
          name: sort
          required: false
          schema:
            type: string
        - in: query
          name: order
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ItemCategoriesResponse'
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /spaces:
    get:
      operationId: findAllSpaces
      parameters:
        - in: query
          name: sort
          required: false
          schema:
            type: string
        - in: query
          name: order
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SpacesResponse'
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /user:
    post:
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
  /user/{userID}:
    get:
      operationId: findByID
      parameters:
        - in: path
          name: userID
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
          description: OK
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Bad Request
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Not Found
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GlobalErrorResponse'
          description: Internal Server Error
      tags:
        - Flakkee Verhuizers
components:
  schemas:
    AddressTypeResponse:
      type: object
      properties:
        addressTypeId:
          type: string
        code:
          type: string
        id:
          type: string
        method:
          type: string
        sequence:
          type: integer
          format: int32
    AddressTypesResponse:
      type: object
      properties:
        addressTypes:
          type: array
          items:
            $ref: '#/components/schemas/AddressTypeResponse'
    GlobalErrorResponse:
      type: object
      properties:
        message:
          type: string
        type:
          type: string
    HouseTypeResponse:
      type: object
      properties:
        houseTypeId:
          type: string
        id:
          type: string
        name:
          type: string
    HouseTypesResponse:
      type: object
      properties:
        houseTypes:
          type: array
          items:
            $ref: '#/components/schemas/HouseTypeResponse'
    ItemCategoriesResponse:
      type: object
      properties:
        itemCategories:
          type: array
          items:
            $ref: '#/components/schemas/ItemCategoryResponse'
    ItemCategoryResponse:
      type: object
      properties:
        custom:
          type: boolean
        icon:
          type: string
        id:
          type: string
        itemCategoryId:
          type: string
        name:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    SpaceResponse:
      type: object
      properties:
        custom:
          type: boolean
        id:
          type: string
        name:
          type: string
        spaceId:
          type: string
    SpacesResponse:
      type: object
      properties:
        spaces:
          type: array
          items:
            $ref: '#/components/schemas/SpaceResponse'
    User:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        email:
          type: string
        firstName:
          type: string
        id:
          type: string
          format: uuid
        lastName:
          type: string
        password:
          type: string
        superAdmin:
          type: boolean
    UserRequest:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
      required:
        - email
        - firstName
        - lastName
        - password
